# Generated by Django 5.0.2 on 2024-03-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Place',
            new_name='place',
        ),
    ]
